server:
  port: 6699
  max-http-header-size: 4048576
spring:
  application:
    name: COMMON-PROVIDER
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      cluster-name: elasticsearch
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

